package ui

import (
	"context"
	"encoding/json"
	"fmt"
	"image/color"
	"sync"

	"gioui.org/layout"
	"gioui.org/unit"

	"github.com/amken3d/immygo/ai"
	"github.com/amken3d/immygo/theme"
)

// PrototypeView generates UI from a natural language description using AI.
// It shows a placeholder while generating, then renders the result.
// Call Eject() to print the generated Go source code for permanent use.
type PrototypeView struct {
	description string
	once        sync.Once
	mu          sync.RWMutex
	view        View
	source      string
	err         error
}

// Prototype creates a view from a natural language description.
// The view is generated asynchronously on first render.
//
//	ui.Prototype("a login form with email and password fields")
func Prototype(description string) *PrototypeView {
	return &PrototypeView{description: description}
}

// Eject prints the generated Go source code to stdout.
// Call this after the prototype has been generated to get permanent code.
func (p *PrototypeView) Eject() {
	p.mu.RLock()
	defer p.mu.RUnlock()
	if p.source != "" {
		fmt.Println("// Generated by ui.Prototype — eject this into your codebase:")
		fmt.Println(p.source)
	} else if p.err != nil {
		fmt.Printf("// Prototype generation failed: %v\n", p.err)
	} else {
		fmt.Println("// Prototype not yet generated")
	}
}

// --- Modifier bridge ---

func (p *PrototypeView) Padding(dp unit.Dp) *Styled       { return Style(p).Padding(dp) }
func (p *PrototypeView) Background(c color.NRGBA) *Styled { return Style(p).Background(c) }
func (p *PrototypeView) Width(dp unit.Dp) *Styled         { return Style(p).Width(dp) }
func (p *PrototypeView) Height(dp unit.Dp) *Styled        { return Style(p).Height(dp) }

func (p *PrototypeView) layout(gtx layout.Context, th *theme.Theme) layout.Dimensions {
	// Kick off async generation on first layout.
	p.once.Do(func() {
		go p.generate()
	})

	p.mu.RLock()
	view := p.view
	err := p.err
	p.mu.RUnlock()

	if view != nil {
		return view.layout(gtx, th)
	}

	// Show placeholder.
	msg := "Generating UI..."
	if err != nil {
		msg = fmt.Sprintf("Generation failed: %v", err)
	}
	return Text(msg).Caption().Center().layout(gtx, th)
}

func (p *PrototypeView) generate() {
	ctx := context.Background()

	prompt := fmt.Sprintf(`Generate a JSON widget tree for the following UI description:

%s

Return a JSON object with this schema:
{"type": "VStack", "props": {"spacing": 12}, "children": [...]}

Supported types: VStack, HStack, Text, Button, Input, Card, Spacer, Divider, Toggle, Checkbox, Progress
Text props: {"text": "...", "style": "title|headline|caption|small|bold|display"}
Button props: {"label": "...", "variant": "primary|secondary|outline|text"}
Input props: {"placeholder": "...", "type": "text|password|search"}
Card props: {"elevation": 1}
Toggle props: {"value": false}
Checkbox props: {"label": "...", "value": false}
Progress props: {"value": 0.5}
VStack/HStack props: {"spacing": 8}

Also return the equivalent Go source code using the ui package.
Format your response as:
TREE:
{...json...}
SOURCE:
`+"```go"+`
...code...
`+"```", p.description)

	response, err := ai.DefaultAssistant().Chat(ctx, prompt)
	if err != nil {
		p.mu.Lock()
		p.err = err
		p.mu.Unlock()
		return
	}

	view, source := parsePrototypeResponse(response)

	p.mu.Lock()
	p.view = view
	p.source = source
	if view == nil {
		p.err = fmt.Errorf("could not parse AI response")
	}
	p.mu.Unlock()
}

// parsePrototypeResponse extracts a JSON tree and Go source from the AI response.
func parsePrototypeResponse(response string) (View, string) {
	// Try to find JSON in the response.
	var tree widgetNode
	jsonStart := -1
	braceCount := 0
	for i, c := range response {
		if c == '{' {
			if braceCount == 0 {
				jsonStart = i
			}
			braceCount++
		} else if c == '}' {
			braceCount--
			if braceCount == 0 && jsonStart >= 0 {
				jsonStr := response[jsonStart : i+1]
				if json.Unmarshal([]byte(jsonStr), &tree) == nil {
					break
				}
				jsonStart = -1
			}
		}
	}

	var view View
	if tree.Type != "" {
		view = buildViewFromJSON(&tree)
	}

	// Extract Go source.
	var source string
	if idx := findCodeBlock(response, "```go"); idx >= 0 {
		source = idx2code(response, idx)
	}

	return view, source
}

func findCodeBlock(s, marker string) int {
	for i := 0; i <= len(s)-len(marker); i++ {
		if s[i:i+len(marker)] == marker {
			return i
		}
	}
	return -1
}

func idx2code(s string, idx int) string {
	start := idx + len("```go")
	for start < len(s) && s[start] != '\n' {
		start++
	}
	start++
	end := start
	for end < len(s)-2 {
		if s[end:end+3] == "```" {
			return s[start:end]
		}
		end++
	}
	return ""
}

// widgetNode is the JSON schema for a widget tree node.
type widgetNode struct {
	Type     string          `json:"type"`
	Props    json.RawMessage `json:"props,omitempty"`
	Children []widgetNode    `json:"children,omitempty"`
}

// buildViewFromJSON recursively maps a JSON widget tree to real Views.
func buildViewFromJSON(node *widgetNode) View {
	switch node.Type {
	case "VStack":
		children := buildChildren(node.Children)
		v := VStack(children...)
		if sp := propsSpacing(node.Props); sp > 0 {
			v.Spacing(unit.Dp(sp))
		}
		return v

	case "HStack":
		children := buildChildren(node.Children)
		h := HStack(children...)
		if sp := propsSpacing(node.Props); sp > 0 {
			h.Spacing(unit.Dp(sp))
		}
		return h

	case "Text":
		props := textProps(node.Props)
		t := Text(props.Text)
		switch props.Style {
		case "title":
			t.Title()
		case "headline":
			t.Headline()
		case "caption":
			t.Caption()
		case "small":
			t.Small()
		case "bold":
			t.Bold()
		case "display":
			t.Display()
		}
		return t

	case "Button":
		props := buttonProps(node.Props)
		b := Button(props.Label)
		switch props.Variant {
		case "secondary":
			b.Secondary()
		case "outline":
			b.Outline()
		case "text":
			b.TextButton()
		}
		return b

	case "Input":
		props := inputProps(node.Props)
		var inp *InputView
		switch props.Type {
		case "password":
			inp = Password()
		case "search":
			inp = Search()
		default:
			inp = Input()
		}
		if props.Placeholder != "" {
			inp.Placeholder(props.Placeholder)
		}
		return inp

	case "Card":
		var child View = Text("")
		if len(node.Children) > 0 {
			children := buildChildren(node.Children)
			child = VStack(children...)
		}
		c := Card(child)
		props := cardProps(node.Props)
		if props.Elevation > 0 {
			c.Elevation(props.Elevation)
		}
		return c

	case "Spacer":
		return Spacer()

	case "Divider":
		return Divider()

	case "Toggle":
		props := toggleProps(node.Props)
		return Toggle(props.Value)

	case "Checkbox":
		props := checkboxProps(node.Props)
		return Checkbox(props.Label, props.Value)

	case "Progress":
		props := progressProps(node.Props)
		return Progress(props.Value)

	default:
		return Text(fmt.Sprintf("[unsupported: %s]", node.Type)).Caption()
	}
}

func buildChildren(nodes []widgetNode) []View {
	views := make([]View, len(nodes))
	for i := range nodes {
		views[i] = buildViewFromJSON(&nodes[i])
	}
	return views
}

// Property extraction helpers.

func propsSpacing(raw json.RawMessage) float32 {
	var p struct {
		Spacing float32 `json:"spacing"`
	}
	if len(raw) > 0 {
		json.Unmarshal(raw, &p)
	}
	return p.Spacing
}

type textPropsT struct {
	Text  string `json:"text"`
	Style string `json:"style"`
}

func textProps(raw json.RawMessage) textPropsT {
	var p textPropsT
	if len(raw) > 0 {
		json.Unmarshal(raw, &p)
	}
	return p
}

type buttonPropsT struct {
	Label   string `json:"label"`
	Variant string `json:"variant"`
}

func buttonProps(raw json.RawMessage) buttonPropsT {
	var p buttonPropsT
	if len(raw) > 0 {
		json.Unmarshal(raw, &p)
	}
	return p
}

type inputPropsT struct {
	Placeholder string `json:"placeholder"`
	Type        string `json:"type"`
}

func inputProps(raw json.RawMessage) inputPropsT {
	var p inputPropsT
	if len(raw) > 0 {
		json.Unmarshal(raw, &p)
	}
	return p
}

type cardPropsT struct {
	Elevation int `json:"elevation"`
}

func cardProps(raw json.RawMessage) cardPropsT {
	var p cardPropsT
	if len(raw) > 0 {
		json.Unmarshal(raw, &p)
	}
	return p
}

type togglePropsT struct {
	Value bool `json:"value"`
}

func toggleProps(raw json.RawMessage) togglePropsT {
	var p togglePropsT
	if len(raw) > 0 {
		json.Unmarshal(raw, &p)
	}
	return p
}

type checkboxPropsT struct {
	Label string `json:"label"`
	Value bool   `json:"value"`
}

func checkboxProps(raw json.RawMessage) checkboxPropsT {
	var p checkboxPropsT
	if len(raw) > 0 {
		json.Unmarshal(raw, &p)
	}
	return p
}

type progressPropsT struct {
	Value float32 `json:"value"`
}

func progressProps(raw json.RawMessage) progressPropsT {
	var p progressPropsT
	if len(raw) > 0 {
		json.Unmarshal(raw, &p)
	}
	return p
}
